### PR TITLE
Revert "Add text file with task 1 URL"

### PR DESCRIPTION
**Pull request by BrandonW24**
Reverts cs361f2019-osu/Fall2019-slab#1

Reverting to confirm the pull request

### CODE REVIEW

**Comment by BiggyFiggy** [comment]
Confirming merge pull request

**Review by BrandonW24 — COMMENTED** [review]
Looks good to me.

**Comment by andrealanz** [comment]
Don't need to revert changes.

**Review by BrandonW24 — COMMENTED** [review]
Looks good to me.

**Review by BrandonW24 — COMMENTED** [review]
Looks good

**Review by BrandonW24 — COMMENTED** [review]
Looks good

**Pull request closed without merging**
